### ISSUE TITLE
Update sttp to 2.0

### ISSUE THREAD

**Issue by adamw** [scalafiddle/scalafiddle-io#48]
How complicated is it to add support for a new version of a library? Is it a matter of updating the https://github.com/scalafiddle/scalafiddle-io/blob/master/libraries.json file (which I could of course do :) ), or are there more steps?

**Comment by ochrons** [comment]
Yeah, just make a PR against that JSON file. Check out previous PRs for examples :)

**Comment by adamw** [comment]
Done, thanks! :)
